### ISSUE TITLE
Local eslint is not used

### ISSUE THREAD

**Issue by IanVS** [AtomLinter/linter-eslint#259]
After upgrading to 5.0.0, it seems that my local installation of ESLint is not being used, because I began getting errors that a shared config could not be found.  Installing that config in ~/.atom/packages/linter-eslint prevents the error message.  Downgrading to `4.0.0` also solves the problem.

**Comment by jokeyrhyme** [comment]
I'm having this issue as well.

> Error: Cannot find module '@jokeyrhyme/eslint-config-es2015' Referenced from: path/to/my/project/.eslintrc
> Referenced from: path/to/my/project/.eslintrc
>   at Function.Module._resolveFilename (module.js:336:15)
>   at Function.Module._load (module.js:286:25)
>   at Module.require (module.js:365:17)
>    at require (module.js:384:17)
>    at readConfigFromFile (/home/ron/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:155:44)
>    at loadConfig (/home/ron/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:176:22)
>    at /home/ron/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:207:46
>    at Array.reduceRight (native)
>    at loadConfig (/home/ron/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:191:36)
>    at getLocalConfig (/home/ron/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:321:23)

Running `$(npm bin)/eslint .` works fine, so this seems to be a linter-eslint issue.

**Comment by paambaati** [comment]
Same here. Local plugins and config modules are not getting picked up after the 5.0.0 upgrade.

**Comment by skuridin** [comment]
:+1:

**Comment by demohi** [comment]
+1

**Comment by hekike** [comment]
+1

**Comment by andmilj** [comment]
+1

**Comment by tinchoz49** [comment]
+1

**Comment by IanVS** [comment]
Hi, thanks everyone for confirming that it's not just me doing something silly.  At this point, further +1 comments don't really add to the discussion though, and just end up causing noise.  Unless you need the fixes in `5.0.0`, you can probably just `apm install linter-eslint@4.0.0` for the time being.  Or, if you need `5.0.0`, you might be able to `cd ~/.atom/packages/linter-eslint && npm install <the package you're being warned about not finding>`.

**Comment by steelbrain** [comment]
Thanks for the bug report, I'll investigate

**Comment by steelbrain** [comment]
I am sorry everyone but I missed this feature while rewriting it, I didn't know this feature even existed to be true, You can expect it back very soon!

**Comment by IanVS** [comment]
Thanks for looking into it.  Just to be clear what we're talking about here, it's this from the README:

> linter-eslint will look for a version of eslint local to your project and use it if it's available.

**Comment by steelbrain** [comment]
If everything goes according to the plan, you can expect a fix in the next few hours :)

**Comment by tinchoz49** [comment]
thanks @steelbrain

**Comment by zaccolley** [comment]
just had this issue ahh, bless you @steelbrain

**Comment by jokeyrhyme** [comment]
Looks like everything is working again in v5.1.0. Thanks!

**Comment by elektronik2k5** [comment]
I can confirm - thank you :)

**Comment by oscar-g** [comment]
I was having these issues with `5.2.5` using the bundled linter and the react plugin.  Solved using @IanVS's instructions:
 ````
cd ~/.atom/packages/linter-eslint/
npm install eslint-plugin-react
````

**Comment by IanVS** [comment]
:+1:

**Comment by alextrastero** [comment]
Works with @IanVS's suggestion :+1:

**Comment by IanVS** [comment]
I'm glad that works for you guys, but really the better solution is to install ESLint and your plugins locally in your project.  Installing the plugins globally or in the package config is kind of a hack.

**Comment by alextrastero** [comment]
The thing is that my project has many contributors and most of them don't need these settings.

**Comment by IanVS** [comment]
In that case another option would be to install eslint and its plugins in the project without adding them to `package.json`.  Just don't ever run `npm prune` if you do that.  :)

**Comment by alextrastero** [comment]
True, good point :) thanks

**Comment by oscar-g** [comment]
Thanks for the tip.

Maybe the README should state this 'best practice'.?

**Comment by SpainTrain** [comment]
PR Welcome :smile_cat:

**Comment by Tiagojdferreira** [comment]
I am having this problem with version 7.0.0

**Comment by IanVS** [comment]
@Tiagojdferreira can you open a new issue with all relevant details?

**Comment by Tiagojdferreira** [comment]
@IanVS sorry, my mistake. It seems I had my atom conf file set to always use the global install.

**Comment by IanVS** [comment]
Cool, glad it's working.

**Comment by ChrisC** [comment]
I'm seeing this issue again in v7.1.3. Locally installed `eslint` v2.5.3 and `eslint-plugin-react` v4.2.3. Neither are installed globally. Tried `npm cache clear` and re-installing but no dice :-(

**Comment by 1beb** [comment]
Same issue v7.1.3

**Comment by IanVS** [comment]
I assume neither of you have the "use global eslint installation" option checked?  If it's not, can you please open a new issue?

**Comment by cweems** [comment]
@1beb @ChrisC same issue. This seemed to work:

`cd ~/.atom/packages/linter-eslint/
npm install
`
And then restart Atom.

**Comment by legendtang** [comment]
In addition to @liyaodong 's solution at https://github.com/eslint/eslint/issues/3782#issuecomment-211169781 and so as @cweems did, if your configs or plugins requires higher version of eslint than `linter-eslint`'s default one. You need to do these additional hacks:

1. Create your own NPM package that packaged all of the dependencies including newer `eslint` and then run `npm i your-npm-package` to install all dependencies you need.
2. Fill in the setting of linter-eslint in` Global Node Installation Path` section with `~/.atom/packages/linter-eslint/node_modules/path-to-your-npm-package`. Tick on `Use global ESLint installation`. Otherwise the plugin

You are able to enjoy the plugins now.

**Comment by IanVS** [comment]
@legendtang, why not install eslint and the plugin as devDependiencies of your project, as recommended?

**Comment by legendtang** [comment]
@IanVS Apparently, not every project are pure JavaScript project, or NPM compatible. Even WebStorm and Sublime Text provide dependent ESLint support. Your aim should focus on the editor not the current project, aren't you?

**Comment by IanVS** [comment]
OK, in that case if you aren't working on a project which multiple contributors need to maintain a consistent JS style, your best option is to install eslint and all of the necessary plugins with the `-g` flag.  So, something like `npm i -g eslint eslint-plugin-whatever`.  Then provide the result of `npm path` for `Global Node Installation Path` and check `Use global ESLint installation`.  There's no need to create your own npm package.

**Comment by legendtang** [comment]
@IanVS Well, they are projects which multiple contributors need to maintain a consistent JS style. And we have different projects that specify different standards with different ESLint plugins version. Migrating and maintaining all sorts of plugins and ESLints require much effort. If not for this, I think installing globally isn't very good practice since once we need to use in every projects that might not share one ESLint version,

**Comment by surdu** [comment]
This problem still exists

**Comment by surdu** [comment]
Manage to fix my problem by running `npm install eslint-plugin-react --save-dev` inside my project's folder. 

Didn't want to install eslint globally ...

**Comment by IanVS** [comment]
This is a very old issue, and was resolved long ago.  If anyone sees a similar problem, please open a new issue and provide all of the information requested in the template.  I'm locking this thread to prevent notifying over 20 people who are subscribed to it.
